version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: jekyll
    versions:
    - 3.9.0
    - 4.0.0.pre.beta1
  - dependency-name: actionview
    versions:
    - 5.2.4.4
    - 5.2.4.5
